Listen = "127.0.0.1:8989"
ReadTimeout = 60000000000
WriteTimeout = 60000000000
IdleTimeout = 60000000000

[Log]
  LogLevel = "6"
  Type = 1
  HookSwitch = true
  [Log.InfluxDB]
    ServerURL = "http://192.168.1.141:8086"
    AuthToken = "jcomkQ-dVBRoCrKSEWMuYxA4COj_EfyCvwgPW5Ql-tT-cCizIjE24rPJQNx8Kkqzz4gCW8YNFq0wcDaHJOcGMQ=="
    Org = "venus-oauth"
    Bucket = "bkt2"
    FlushInterval = 30000000000
    BatchSize = 100

[DB]
  Type = "badger"
  DSN = "root:111111@(127.0.0.1:3306)/auth_server?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci&readTimeout=10s&writeTimeout=10s"
  MaxOpenConns = 64
  MaxIdleConns = 128
  MaxLifeTime = 120000000000
  MaxIdleTime = 30000000000
  Debug = false
